#!/usr/bin/env python3
"""Safely update lib/styles/custom.yaml for Marketing Analytics Pack.

The script copies either default.yaml or executive.yaml into custom.yaml, updates
only the brand block, and optionally renders a small preview chart.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
STYLE_DIR = REPO_ROOT / "lib" / "styles"
HEX_RE = re.compile(r"^#[0-9a-fA-F]{6}$")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Update Marketing Analytics Pack custom style.")
    parser.add_argument("--base", choices=["default", "executive"], default="default")
    parser.add_argument("--primary", help="Primary brand color, e.g. #2563eb")
    parser.add_argument("--logo", default=None, help="Logo path to store")
    parser.add_argument("--clear-logo", action="store_true", help="Clear logo_path in the custom style")
    parser.add_argument("--font", default=None, help="Font family to store")
    parser.add_argument("--preview", default=None, help="Optional PNG path for a preview chart")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    base_path = STYLE_DIR / f"{args.base}.yaml"
    custom_path = STYLE_DIR / "custom.yaml"

    if not base_path.exists():
        print(f"Base style not found: {base_path}", file=sys.stderr)
        return 2

    primary = args.primary.strip() if args.primary else None
    if primary and not HEX_RE.match(primary):
        print("Primary color must be a 6-character hex code like #2563eb.", file=sys.stderr)
        return 2

    data = base_path.read_text(encoding="utf-8").splitlines()
    updated = _update_top_level_scalars(
        data,
        {
            "name": "custom",
            "description": f"User-editable custom style generated from {args.base}.",
        },
    )
    brand_updates = {}
    if primary:
        brand_updates["primary_hex"] = primary.lower()
    if args.clear_logo:
        brand_updates["logo_path"] = ""
    elif args.logo is not None:
        brand_updates["logo_path"] = args.logo
    if args.font:
        brand_updates["font_family"] = args.font
    updated = _update_nested_scalars(updated, "brand", brand_updates)

    header = [
        "# Custom style - generated by skills/style-picker/scripts/set_style.py.",
        "# The /style command modifies only the brand block by default.",
    ]
    custom_path.write_text("\n".join(header + updated) + "\n", encoding="utf-8")

    print(f"Updated {custom_path}")
    print(f"Base style: {args.base}")
    if brand_updates:
        for key, value in brand_updates.items():
            print(f"{key}: {value}")

    if args.preview:
        _render_preview(args.preview)
    return 0


def _quote(value: str) -> str:
    return '"' + value.replace('"', '\\"') + '"'


def _update_top_level_scalars(lines: list[str], updates: dict[str, str]) -> list[str]:
    out: list[str] = []
    for line in lines:
        stripped = line.strip()
        if not line.startswith(" ") and ":" in stripped:
            key = stripped.split(":", 1)[0].strip()
            if key in updates:
                out.append(f"{key}: {_quote(updates[key])}")
                continue
        out.append(line)
    return out


def _update_nested_scalars(lines: list[str], section: str, updates: dict[str, str]) -> list[str]:
    if not updates:
        return lines
    out: list[str] = []
    in_section = False
    seen = set()
    for line in lines:
        stripped = line.strip()
        if not line.startswith(" ") and stripped == f"{section}:":
            in_section = True
            out.append(line)
            continue
        if in_section and line and not line.startswith(" "):
            for key, value in updates.items():
                if key not in seen:
                    out.append(f"  {key}: {_quote(value)}")
            in_section = False
        if in_section and stripped and ":" in stripped:
            key = stripped.split(":", 1)[0].strip()
            if key in updates:
                out.append(f"  {key}: {_quote(updates[key])}")
                seen.add(key)
                continue
        out.append(line)
    if in_section:
        for key, value in updates.items():
            if key not in seen:
                out.append(f"  {key}: {_quote(value)}")
    return out


def _render_preview(path_text: str) -> None:
    try:
        import matplotlib.pyplot as plt
    except ImportError:
        print("Preview skipped: matplotlib is not installed.", file=sys.stderr)
        return

    sys.path.insert(0, str(REPO_ROOT / "lib"))
    from visualize import chart_tokens, layout, load_style, matplotlib_rc_params, palette, typography

    style = load_style("custom")
    colors = palette(style)
    chart = chart_tokens(style)
    type_tokens = typography(style)
    layout_tokens = layout(style)
    plt.rcParams.update(matplotlib_rc_params(style))

    output = Path(path_text)
    if not output.is_absolute():
        output = REPO_ROOT / output
    output.parent.mkdir(parents=True, exist_ok=True)

    fig, ax = plt.subplots(
        figsize=(layout_tokens.get("figure_width", 9), layout_tokens.get("figure_height", 5)),
        dpi=layout_tokens.get("dpi", 160),
    )
    labels = ["Paid search", "Email", "Organic", "Paid social"]
    values = [1240, 920, 760, 680]
    bars = ax.bar(labels, values, color=colors[: len(labels)])
    ax.set_title("Custom style preview", pad=layout_tokens.get("title_pad", 14), loc="left")
    ax.set_ylabel("Conversions")
    ax.grid(axis="y", linewidth=0.8, alpha=0.8)
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)
    for bar in bars:
        height = bar.get_height()
        ax.text(
            bar.get_x() + bar.get_width() / 2,
            height,
            f"{height:,.0f}",
            ha="center",
            va="bottom",
            fontsize=type_tokens.get("note_size", 8),
            color=chart.get("muted", "#6b7280"),
        )
    fig.tight_layout()
    fig.savefig(output, bbox_inches="tight")
    plt.close(fig)
    print(f"Preview written: {output}")


if __name__ == "__main__":
    raise SystemExit(main())
